"""add indexes

Revision ID: 6ee2659b9c3e
Revises: 54525c48f271
Create Date: 2026-07-10 12:00:35.619727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ee2659b9c3e'
down_revision: Union[str, Sequence[str], None] = '54525c48f271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_docs')
    op.create_index('idx_campaigns_is_active', 'campaigns', ['is_active'], unique=False)
    op.create_index('idx_campaigns_niche_type', 'campaigns', ['niche_type'], unique=False)
    op.create_index('idx_dialogs_campaign_id', 'dialogs', ['campaign_id'], unique=False)
    op.create_index('idx_dialogs_campaign_status', 'dialogs', ['campaign_id', 'status'], unique=False)
    op.create_index('idx_dialogs_lead_id', 'dialogs', ['lead_id'], unique=False)
    op.create_index('idx_dialogs_started_at', 'dialogs', ['started_at'], unique=False)
    op.create_index('idx_dialogs_status', 'dialogs', ['status'], unique=False)
    op.create_index('idx_leads_campaign_id', 'leads', ['campaign_id'], unique=False)
    op.create_index('idx_leads_campaign_status', 'leads', ['campaign_id', 'status'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_index('idx_messages_dialog_id', 'messages', ['dialog_id'], unique=False)
    op.create_index('idx_messages_timestamp', 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_messages_timestamp', table_name='messages')
    op.drop_index('idx_messages_dialog_id', table_name='messages')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_campaign_status', table_name='leads')
    op.drop_index('idx_leads_campaign_id', table_name='leads')
    op.drop_index('idx_dialogs_status', table_name='dialogs')
    op.drop_index('idx_dialogs_started_at', table_name='dialogs')
    op.drop_index('idx_dialogs_lead_id', table_name='dialogs')
    op.drop_index('idx_dialogs_campaign_status', table_name='dialogs')
    op.drop_index('idx_dialogs_campaign_id', table_name='dialogs')
    op.drop_index('idx_campaigns_niche_type', table_name='campaigns')
    op.drop_index('idx_campaigns_is_active', table_name='campaigns')
    op.create_table('knowledge_docs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('knowledge_docs_campaign_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_docs_pkey'))
    )
    # ### end Alembic commands ###
